# Generated by Django 2.2.7 on 2019-11-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='Date',
        ),
    ]
