# Generated by Django 2.2.7 on 2019-11-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191118_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condittion',
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='new', max_length=100),
        ),
    ]
