# Generated by Django 2.2.7 on 2019-11-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191118_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categrory',
            field=models.CharField(choices=[('Iphone', 'Iphone'), ('Samsung', 'Sumsung'), ('Infinix', 'Infinix'), ('Tecno', 'Tecno')], default='Iphone', max_length=100),
        ),
    ]
