# Generated by Django 2.2.7 on 2019-11-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191118_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categrory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Categrory'),
        ),
    ]
