# Generated by Django 2.2.7 on 2019-11-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_categrory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categrory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'cateory', 'verbose_name_plural': 'Categories'},
        ),
    ]
