# Generated by Django 2.2.7 on 2019-11-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
