# Generated by Django 2.2.7 on 2019-11-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20191118_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='proudct',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
