# Generated by Django 2.2.7 on 2019-11-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Owner',
            new_name='owner',
        ),
    ]
