# Generated by Django 2.2.7 on 2019-11-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categrogry_name',
            new_name='categogry_name',
        ),
    ]
