# Generated by Django 2.2.7 on 2019-11-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20191120_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categrory',
            new_name='category',
        ),
    ]
