# Generated by Django 2.2.7 on 2019-11-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20191120_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categogry_name',
            new_name='category_name',
        ),
    ]
