# Generated by Django 2.2.7 on 2019-11-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
