# Generated by Django 2.2.7 on 2019-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20191123_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Region',
            field=models.CharField(choices=[('Bono Region', 'Bono Region'), ('Ashante Region', 'Ashante Region'), ('Upper East', 'Upper East')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
