# Generated by Django 2.2.7 on 2019-11-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20191124_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Region',
            new_name='region',
        ),
    ]
